sudo: no
language: python
cache: pip

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

install:
 - pip install -r dev_requirements.txt

script: 
 - nosetests --rednose --with-coverage --cover-package=transip
 - pylint --rcfile=.pylintrc transip

# Deploy a new release to PyPi for every new tag on the 'master' branch on the
# repository 'benkonrath/transip-api'.
deploy:
  provider: pypi
  user: roaldnefs
  password:
    secure: "ej8lf26roItqLNrfsLxFVNWjLVipoVo62wNGsobj2x3AcuzqVRreHw3pTapmDXjNf9/fpsDLHx14ljI7k+WfUNwB51depqwleWG5cEZyNMP1A365a/j7QfGiE/aiS/Nmi0A6U7eiovku9PiBY0TL3JqU/Mx6w9dA0C9yCRkxIKg="
  on:
    repo: benkonrath/transip-api
    tags: true
    branch: master
    python: 3.6
